package model;
// Generated 17-may-2016 15:46:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private int idPrestamo;
     private Libro libro;
     private Usuario usuario;
     private Boolean PActivo;
     private Set<Intercambio> intercambios = new HashSet<Intercambio>(0);

    public Prestamo() {
    }

	
    public Prestamo(int idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Prestamo(int idPrestamo, Libro libro, Usuario usuario, Boolean PActivo, Set<Intercambio> intercambios) {
       this.idPrestamo = idPrestamo;
       this.libro = libro;
       this.usuario = usuario;
       this.PActivo = PActivo;
       this.intercambios = intercambios;
    }
   
    public int getIdPrestamo() {
        return this.idPrestamo;
    }
    
    public void setIdPrestamo(int idPrestamo) {
        this.idPrestamo = idPrestamo;
    }
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Boolean getPActivo() {
        return this.PActivo;
    }
    
    public void setPActivo(Boolean PActivo) {
        this.PActivo = PActivo;
    }
    public Set<Intercambio> getIntercambios() {
        return this.intercambios;
    }
    
    public void setIntercambios(Set<Intercambio> intercambios) {
        this.intercambios = intercambios;
    }




}


