package modelo;
// Generated 05-jun-2016 23:07:54 by Hibernate Tools 4.3.1



/**
 * Intercambio generated by hbm2java
 */
public class Intercambio  implements java.io.Serializable {


     private int idIntercambio;
     private Libro libro;
     private Prestamo prestamo;

    public Intercambio() {
    }

	
    public Intercambio(int idIntercambio) {
        this.idIntercambio = idIntercambio;
    }
    public Intercambio(int idIntercambio, Libro libro, Prestamo prestamo) {
       this.idIntercambio = idIntercambio;
       this.libro = libro;
       this.prestamo = prestamo;
    }
   
    public int getIdIntercambio() {
        return this.idIntercambio;
    }
    
    public void setIdIntercambio(int idIntercambio) {
        this.idIntercambio = idIntercambio;
    }
    public Libro getLibro() {
        return this.libro;
    }
    
    public void setLibro(Libro libro) {
        this.libro = libro;
    }
    public Prestamo getPrestamo() {
        return this.prestamo;
    }
    
    public void setPrestamo(Prestamo prestamo) {
        this.prestamo = prestamo;
    }




}


