package modelo;
// Generated 18/05/2016 02:01:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro  implements java.io.Serializable {


     private int idLibro;
     private Usuario usuario;
     private String LTitulo;
     private String LAutor;
     private String LEditorial;
     private String LIsbn;
     private String LAnho;
     private Integer NEdicion;
     private Integer LEvalucionContenido;
     private Integer LEvaluacionRedaccion;
     private String LResehna;
     private String LPablasClave;
     private String LFoto;
     private String LMapaUbicacion;
     private Boolean LOferta;
     private Set<Prestamo> prestamos = new HashSet<Prestamo>(0);
     private Set<Intercambio> intercambios = new HashSet<Intercambio>(0);

    public Libro() {
    }

	
    public Libro(int idLibro) {
        this.idLibro = idLibro;
    }
    public Libro(int idLibro, Usuario usuario, String LTitulo, String LAutor, String LEditorial, String LIsbn, String LAnho, Integer NEdicion, Integer LEvalucionContenido, Integer LEvaluacionRedaccion, String LResehna, String LPablasClave, String LFoto, String LMapaUbicacion, Boolean LOferta, Set<Prestamo> prestamos, Set<Intercambio> intercambios) {
       this.idLibro = idLibro;
       this.usuario = usuario;
       this.LTitulo = LTitulo;
       this.LAutor = LAutor;
       this.LEditorial = LEditorial;
       this.LIsbn = LIsbn;
       this.LAnho = LAnho;
       this.NEdicion = NEdicion;
       this.LEvalucionContenido = LEvalucionContenido;
       this.LEvaluacionRedaccion = LEvaluacionRedaccion;
       this.LResehna = LResehna;
       this.LPablasClave = LPablasClave;
       this.LFoto = LFoto;
       this.LMapaUbicacion = LMapaUbicacion;
       this.LOferta = LOferta;
       this.prestamos = prestamos;
       this.intercambios = intercambios;
    }
   
    public int getIdLibro() {
        return this.idLibro;
    }
    
    public void setIdLibro(int idLibro) {
        this.idLibro = idLibro;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getLTitulo() {
        return this.LTitulo;
    }
    
    public void setLTitulo(String LTitulo) {
        this.LTitulo = LTitulo;
    }
    public String getLAutor() {
        return this.LAutor;
    }
    
    public void setLAutor(String LAutor) {
        this.LAutor = LAutor;
    }
    public String getLEditorial() {
        return this.LEditorial;
    }
    
    public void setLEditorial(String LEditorial) {
        this.LEditorial = LEditorial;
    }
    public String getLIsbn() {
        return this.LIsbn;
    }
    
    public void setLIsbn(String LIsbn) {
        this.LIsbn = LIsbn;
    }
    public String getLAnho() {
        return this.LAnho;
    }
    
    public void setLAnho(String LAnho) {
        this.LAnho = LAnho;
    }
    public Integer getNEdicion() {
        return this.NEdicion;
    }
    
    public void setNEdicion(Integer NEdicion) {
        this.NEdicion = NEdicion;
    }
    public Integer getLEvalucionContenido() {
        return this.LEvalucionContenido;
    }
    
    public void setLEvalucionContenido(Integer LEvalucionContenido) {
        this.LEvalucionContenido = LEvalucionContenido;
    }
    public Integer getLEvaluacionRedaccion() {
        return this.LEvaluacionRedaccion;
    }
    
    public void setLEvaluacionRedaccion(Integer LEvaluacionRedaccion) {
        this.LEvaluacionRedaccion = LEvaluacionRedaccion;
    }
    public String getLResehna() {
        return this.LResehna;
    }
    
    public void setLResehna(String LResehna) {
        this.LResehna = LResehna;
    }
    public String getLPablasClave() {
        return this.LPablasClave;
    }
    
    public void setLPablasClave(String LPablasClave) {
        this.LPablasClave = LPablasClave;
    }
    public String getLFoto() {
        return this.LFoto;
    }
    
    public void setLFoto(String LFoto) {
        this.LFoto = LFoto;
    }
    public String getLMapaUbicacion() {
        return this.LMapaUbicacion;
    }
    
    public void setLMapaUbicacion(String LMapaUbicacion) {
        this.LMapaUbicacion = LMapaUbicacion;
    }
    public Boolean getLOferta() {
        return this.LOferta;
    }
    
    public void setLOferta(Boolean LOferta) {
        this.LOferta = LOferta;
    }
    public Set<Prestamo> getPrestamos() {
        return this.prestamos;
    }
    
    public void setPrestamos(Set<Prestamo> prestamos) {
        this.prestamos = prestamos;
    }
    public Set<Intercambio> getIntercambios() {
        return this.intercambios;
    }
    
    public void setIntercambios(Set<Intercambio> intercambios) {
        this.intercambios = intercambios;
    }




}


