package modelo;
// Generated 05-jun-2016 23:07:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String UNombre;
     private String UApellido;
     private String UTelefono;
     private String UContrasenha;
     private String UCorreo;
     private Integer UCalificaficacion;
     private Integer UNumeroCalificacion;
     private Set<Prestamo> prestamosForIdUsuarioPrestador = new HashSet<Prestamo>(0);
     private Set<Libro> libros = new HashSet<Libro>(0);
     private Set<Prestamo> prestamosForIdUsuarioSolicitante = new HashSet<Prestamo>(0);

    public Usuario() {
    }

	
    public Usuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario(int idUsuario, String UNombre, String UApellido, String UTelefono, String UContrasenha, String UCorreo, Integer UCalificaficacion, Integer UNumeroCalificacion, Set<Prestamo> prestamosForIdUsuarioPrestador, Set<Libro> libros, Set<Prestamo> prestamosForIdUsuarioSolicitante) {
       this.idUsuario = idUsuario;
       this.UNombre = UNombre;
       this.UApellido = UApellido;
       this.UTelefono = UTelefono;
       this.UContrasenha = UContrasenha;
       this.UCorreo = UCorreo;
       this.UCalificaficacion = UCalificaficacion;
       this.UNumeroCalificacion = UNumeroCalificacion;
       this.prestamosForIdUsuarioPrestador = prestamosForIdUsuarioPrestador;
       this.libros = libros;
       this.prestamosForIdUsuarioSolicitante = prestamosForIdUsuarioSolicitante;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUNombre() {
        return this.UNombre;
    }
    
    public void setUNombre(String UNombre) {
        this.UNombre = UNombre;
    }
    public String getUApellido() {
        return this.UApellido;
    }
    
    public void setUApellido(String UApellido) {
        this.UApellido = UApellido;
    }
    public String getUTelefono() {
        return this.UTelefono;
    }
    
    public void setUTelefono(String UTelefono) {
        this.UTelefono = UTelefono;
    }
    public String getUContrasenha() {
        return this.UContrasenha;
    }
    
    public void setUContrasenha(String UContrasenha) {
        this.UContrasenha = UContrasenha;
    }
    public String getUCorreo() {
        return this.UCorreo;
    }
    
    public void setUCorreo(String UCorreo) {
        this.UCorreo = UCorreo;
    }
    public Integer getUCalificaficacion() {
        return this.UCalificaficacion;
    }
    
    public void setUCalificaficacion(Integer UCalificaficacion) {
        this.UCalificaficacion = UCalificaficacion;
    }
    public Integer getUNumeroCalificacion() {
        return this.UNumeroCalificacion;
    }
    
    public void setUNumeroCalificacion(Integer UNumeroCalificacion) {
        this.UNumeroCalificacion = UNumeroCalificacion;
    }
    public Set<Prestamo> getPrestamosForIdUsuarioPrestador() {
        return this.prestamosForIdUsuarioPrestador;
    }
    
    public void setPrestamosForIdUsuarioPrestador(Set<Prestamo> prestamosForIdUsuarioPrestador) {
        this.prestamosForIdUsuarioPrestador = prestamosForIdUsuarioPrestador;
    }
    public Set<Libro> getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set<Libro> libros) {
        this.libros = libros;
    }
    public Set<Prestamo> getPrestamosForIdUsuarioSolicitante() {
        return this.prestamosForIdUsuarioSolicitante;
    }
    
    public void setPrestamosForIdUsuarioSolicitante(Set<Prestamo> prestamosForIdUsuarioSolicitante) {
        this.prestamosForIdUsuarioSolicitante = prestamosForIdUsuarioSolicitante;
    }




}


